org: author
service: aws-server-template

frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  profile: serverlessTemplate
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:AdminUpdateUserAttributes
        - cognito-idp:GlobalSignOut
        - cognito-idp:ListUsers
      Resource:
        - arn:aws:cognito-idp:us-east-1:884252207764:userpool/us-east-1_iLGqg20bi

functions:
  registerUser:
    handler: src/handlers/authHandler.registerHandler
    events:
      - http:
          path: auth/register
          method: post

  confirmRegister:
    handler: src/handlers/authHandler.confirmRegisterHandler
    events:
      - http:
          path: auth/register/confirm
          method: post

  updateUserGroup:
    handler: src/handlers/authHandler.updateGroupHandler
    events:
      - http:
          path: auth/updateGroup
          method: post

  loginUser:
    handler: src/handlers/authHandler.loginHandler
    events:
      - http:
          path: auth/login
          method: post

  logoutUser:
    handler: src/handlers/authHandler.logoutHandler
    events:
      - http:
          path: auth/logout
          method: post
